
"""
Create AI_insights_report.pdf from charts and summary text in ../outputs/
"""

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os

OUT = "../outputs"
PDF_PATH = "../AI_insights_report.pdf"

def draw_image(c, img_path, x, y, w):
    try:
        img = ImageReader(img_path)
        iw, ih = img.getSize()
        h = w * (ih / iw)
        c.drawImage(img, x, y - h, width=w, height=h)
        return h
    except Exception as e:
        print("Image draw error:", e)
        return 0

def main():
    c = canvas.Canvas(PDF_PATH, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width/2, height-60, "AI Insights Report")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width/2, height-80, "Intelligent Customer Feedback Analysis System")
    y = height - 110

    
    summary_file = os.path.join(OUT, "insights_summary.txt")
    if os.path.exists(summary_file):
        with open(summary_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
        c.setFont("Helvetica", 11)
        for line in lines:
            if y < 120:
                c.showPage()
                y = height - 60
            c.drawString(40, y, line.strip())
            y -= 14

    
    imgs = ["lda_topics.png", "daily_avg_score.png", "prophet_forecast.png", "prophet_components.png", "arima_forecast.png"]
    for img in imgs:
        img_path = os.path.join(OUT, img)
        if os.path.exists(img_path):
            if y < 300:
                c.showPage()
                y = height - 60
            
            h = draw_image(c, img_path, 40, y, width*0.85)
            y -= (h + 20)

    # Footer
    c.showPage()
    c.setFont("Helvetica", 9)
    c.drawString(40, height-40, "Generated by Intelligent Customer Feedback Analysis System")

    c.save()
    print(" PDF report created at", PDF_PATH)

if __name__ == "__main__":
    main()
